# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'administrative.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(809, 865)
        self.actionMuokkaa = QAction(MainWindow)
        self.actionMuokkaa.setObjectName(u"actionMuokkaa")
        self.actionTietoja_ohjelmasta = QAction(MainWindow)
        self.actionTietoja_ohjelmasta.setObjectName(u"actionTietoja_ohjelmasta")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.valikko_2 = QTabWidget(self.centralwidget)
        self.valikko_2.setObjectName(u"valikko_2")
        self.valikko_2.setGeometry(QRect(0, 0, 821, 881))
        self.studentTab_2 = QWidget()
        self.studentTab_2.setObjectName(u"studentTab_2")
        self.studentTab_2.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.valikko_3 = QTabWidget(self.studentTab_2)
        self.valikko_3.setObjectName(u"valikko_3")
        self.valikko_3.setGeometry(QRect(-10, -20, 761, 821))
        self.studentTab_3 = QWidget()
        self.studentTab_3.setObjectName(u"studentTab_3")
        self.valikko_4 = QTabWidget(self.studentTab_3)
        self.valikko_4.setObjectName(u"valikko_4")
        self.valikko_4.setGeometry(QRect(10, -30, 721, 821))
        self.studentTab_4 = QWidget()
        self.studentTab_4.setObjectName(u"studentTab_4")
        self.valikko_4.addTab(self.studentTab_4, "")
        self.vechileTab_4 = QWidget()
        self.vechileTab_4.setObjectName(u"vechileTab_4")
        self.valikko_4.addTab(self.vechileTab_4, "")
        self.reportsTab_4 = QWidget()
        self.reportsTab_4.setObjectName(u"reportsTab_4")
        self.ssnLabel = QLabel(self.reportsTab_4)
        self.ssnLabel.setObjectName(u"ssnLabel")
        self.ssnLabel.setGeometry(QRect(20, 40, 81, 16))
        font = QFont()
        font.setPointSize(9)
        self.ssnLabel.setFont(font)
        self.firstnameLabel = QLabel(self.reportsTab_4)
        self.firstnameLabel.setObjectName(u"firstnameLabel")
        self.firstnameLabel.setGeometry(QRect(20, 70, 81, 16))
        self.firstnameLabel.setFont(font)
        self.lastNameLabel = QLabel(self.reportsTab_4)
        self.lastNameLabel.setObjectName(u"lastNameLabel")
        self.lastNameLabel.setGeometry(QRect(20, 100, 81, 16))
        self.lastNameLabel.setFont(font)
        self.grupLabel = QLabel(self.reportsTab_4)
        self.grupLabel.setObjectName(u"grupLabel")
        self.grupLabel.setGeometry(QRect(20, 130, 47, 13))
        self.grupLabel.setFont(font)
        self.vechileClassLabel = QLabel(self.reportsTab_4)
        self.vechileClassLabel.setObjectName(u"vechileClassLabel")
        self.vechileClassLabel.setGeometry(QRect(20, 160, 91, 16))
        self.vechileClassLabel.setFont(font)
        self.ssnLineEdit = QLineEdit(self.reportsTab_4)
        self.ssnLineEdit.setObjectName(u"ssnLineEdit")
        self.ssnLineEdit.setGeometry(QRect(110, 40, 151, 20))
        self.fistNameLineEdit = QLineEdit(self.reportsTab_4)
        self.fistNameLineEdit.setObjectName(u"fistNameLineEdit")
        self.fistNameLineEdit.setGeometry(QRect(110, 70, 151, 20))
        self.lastNamelineEdit_ = QLineEdit(self.reportsTab_4)
        self.lastNamelineEdit_.setObjectName(u"lastNamelineEdit_")
        self.lastNamelineEdit_.setGeometry(QRect(110, 100, 151, 20))
        self.vechileClassLineEdit = QLineEdit(self.reportsTab_4)
        self.vechileClassLineEdit.setObjectName(u"vechileClassLineEdit")
        self.vechileClassLineEdit.setGeometry(QRect(110, 160, 151, 20))
        self.groupComoBox = QComboBox(self.reportsTab_4)
        self.groupComoBox.setObjectName(u"groupComoBox")
        self.groupComoBox.setGeometry(QRect(110, 130, 151, 22))
        self.tableWidget_2 = QTableWidget(self.reportsTab_4)
        if (self.tableWidget_2.columnCount() < 5):
            self.tableWidget_2.setColumnCount(5)
        if (self.tableWidget_2.rowCount() < 10):
            self.tableWidget_2.setRowCount(10)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(20, 260, 601, 341))
        self.tableWidget_2.setRowCount(10)
        self.tableWidget_2.setColumnCount(5)
        self.label_32 = QLabel(self.reportsTab_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 230, 131, 16))
        self.label_32.setFont(font)
        self.savePushButton = QPushButton(self.reportsTab_4)
        self.savePushButton.setObjectName(u"savePushButton")
        self.savePushButton.setGeometry(QRect(270, 160, 81, 23))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(True)
        self.savePushButton.setFont(font1)
        self.savePushButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.savePushButton.setStyleSheet(u"background-color: rgb(51, 117, 216);\n"
"color: rgb(245, 245, 245);")
        self.valikko_4.addTab(self.reportsTab_4, "")
        self.valikko_3.addTab(self.studentTab_3, "")
        self.vechileTab_3 = QWidget()
        self.vechileTab_3.setObjectName(u"vechileTab_3")
        self.vechileTab_3.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.valikko_3.addTab(self.vechileTab_3, "")
        self.reportsTab_3 = QWidget()
        self.reportsTab_3.setObjectName(u"reportsTab_3")
        self.label_11 = QLabel(self.reportsTab_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 40, 81, 16))
        self.label_12 = QLabel(self.reportsTab_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 70, 81, 16))
        self.label_13 = QLabel(self.reportsTab_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 100, 81, 16))
        self.label_14 = QLabel(self.reportsTab_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 130, 47, 13))
        self.label_15 = QLabel(self.reportsTab_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 160, 91, 16))
        self.lineEdit_5 = QLineEdit(self.reportsTab_3)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(110, 40, 113, 20))
        self.lineEdit_9 = QLineEdit(self.reportsTab_3)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(110, 70, 113, 20))
        self.lineEdit_10 = QLineEdit(self.reportsTab_3)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(110, 100, 113, 20))
        self.lineEdit_11 = QLineEdit(self.reportsTab_3)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(110, 160, 113, 20))
        self.comboBox_3 = QComboBox(self.reportsTab_3)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(110, 130, 111, 22))
        self.valikko_3.addTab(self.reportsTab_3, "")
        self.valikko_2.addTab(self.studentTab_2, "")
        self.vechileTab_2 = QWidget()
        self.vechileTab_2.setObjectName(u"vechileTab_2")
        self.vechileTab_2.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.registerNumberLabel = QLabel(self.vechileTab_2)
        self.registerNumberLabel.setObjectName(u"registerNumberLabel")
        self.registerNumberLabel.setGeometry(QRect(10, 30, 101, 16))
        self.registerNumberLabel.setFont(font)
        self.markeLabel = QLabel(self.vechileTab_2)
        self.markeLabel.setObjectName(u"markeLabel")
        self.markeLabel.setGeometry(QRect(10, 60, 47, 13))
        self.markeLabel.setFont(font)
        self.modelLabel = QLabel(self.vechileTab_2)
        self.modelLabel.setObjectName(u"modelLabel")
        self.modelLabel.setGeometry(QRect(10, 90, 47, 13))
        self.modelLabel.setFont(font)
        self.yearModel = QLabel(self.vechileTab_2)
        self.yearModel.setObjectName(u"yearModel")
        self.yearModel.setGeometry(QRect(10, 120, 71, 16))
        self.yearModel.setFont(font)
        self.registerNumberlineEdit = QLineEdit(self.vechileTab_2)
        self.registerNumberlineEdit.setObjectName(u"registerNumberlineEdit")
        self.registerNumberlineEdit.setGeometry(QRect(110, 30, 141, 20))
        self.markeLineEdit = QLineEdit(self.vechileTab_2)
        self.markeLineEdit.setObjectName(u"markeLineEdit")
        self.markeLineEdit.setGeometry(QRect(110, 60, 141, 20))
        self.modelLineEdit = QLineEdit(self.vechileTab_2)
        self.modelLineEdit.setObjectName(u"modelLineEdit")
        self.modelLineEdit.setGeometry(QRect(110, 90, 141, 20))
        self.yearModelLineEdit = QLineEdit(self.vechileTab_2)
        self.yearModelLineEdit.setObjectName(u"yearModelLineEdit")
        self.yearModelLineEdit.setGeometry(QRect(110, 120, 141, 20))
        self.personCountLabel = QLabel(self.vechileTab_2)
        self.personCountLabel.setObjectName(u"personCountLabel")
        self.personCountLabel.setGeometry(QRect(10, 150, 81, 16))
        self.personCountLabel.setFont(font)
        self.personCountLineEdit = QLineEdit(self.vechileTab_2)
        self.personCountLineEdit.setObjectName(u"personCountLineEdit")
        self.personCountLineEdit.setGeometry(QRect(110, 150, 141, 20))
        self.printSaveButton = QPushButton(self.vechileTab_2)
        self.printSaveButton.setObjectName(u"printSaveButton")
        self.printSaveButton.setGeometry(QRect(260, 150, 81, 23))
        self.printSaveButton.setFont(font1)
        self.printSaveButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.printSaveButton.setStyleSheet(u"background-color: rgb(94, 172, 255);\n"
"color: rgb(247, 247, 247);")
        self.printBarcodeButton = QPushButton(self.vechileTab_2)
        self.printBarcodeButton.setObjectName(u"printBarcodeButton")
        self.printBarcodeButton.setGeometry(QRect(260, 120, 81, 23))
        self.printBarcodeButton.setFont(font)
        self.printBarcodeButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.printBarcodeButton.setStyleSheet(u"background-color: rgb(255, 140, 46);\n"
"color: rgb(255, 255, 255);")
        self.tableWidget = QTableWidget(self.vechileTab_2)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        if (self.tableWidget.rowCount() < 10):
            self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 220, 751, 331))
        self.tableWidget.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.BlankCursor))
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(5)
        self.label_31 = QLabel(self.vechileTab_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 200, 111, 16))
        self.valikko_2.addTab(self.vechileTab_2, "")
        self.reportsTab_2 = QWidget()
        self.reportsTab_2.setObjectName(u"reportsTab_2")
        self.label = QLabel(self.reportsTab_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 71, 16))
        font2 = QFont()
        font2.setPointSize(10)
        self.label.setFont(font2)
        self.startDateEdit = QDateEdit(self.reportsTab_2)
        self.startDateEdit.setObjectName(u"startDateEdit")
        self.startDateEdit.setGeometry(QRect(20, 100, 151, 31))
        self.startDateEdit.setCalendarPopup(True)
        self.startDateEdit.setDate(QDate(2025, 1, 1))
        self.reportTypecomboBox = QComboBox(self.reportsTab_2)
        self.reportTypecomboBox.setObjectName(u"reportTypecomboBox")
        self.reportTypecomboBox.setGeometry(QRect(20, 30, 151, 22))
        self.statDateLable = QLabel(self.reportsTab_2)
        self.statDateLable.setObjectName(u"statDateLable")
        self.statDateLable.setGeometry(QRect(20, 80, 71, 16))
        self.statDateLable.setFont(font2)
        self.endDateEdit = QDateEdit(self.reportsTab_2)
        self.endDateEdit.setObjectName(u"endDateEdit")
        self.endDateEdit.setGeometry(QRect(220, 100, 151, 31))
        self.endDateEdit.setCalendarPopup(True)
        self.endDateEdit.setDate(QDate(2025, 1, 1))
        self.endDateLabel = QLabel(self.reportsTab_2)
        self.endDateLabel.setObjectName(u"endDateLabel")
        self.endDateLabel.setGeometry(QRect(220, 80, 71, 16))
        self.endDateLabel.setFont(font2)
        self.printResultPushButton = QPushButton(self.reportsTab_2)
        self.printResultPushButton.setObjectName(u"printResultPushButton")
        self.printResultPushButton.setGeometry(QRect(390, 100, 81, 31))
        self.printResultPushButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.printResultPushButton.setStyleSheet(u"background-color: rgb(85, 85, 255);\n"
"color: rgb(249, 249, 249);")
        self.tableWidget_3 = QTableWidget(self.reportsTab_2)
        if (self.tableWidget_3.columnCount() < 6):
            self.tableWidget_3.setColumnCount(6)
        if (self.tableWidget_3.rowCount() < 22):
            self.tableWidget_3.setRowCount(22)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(20, 170, 731, 331))
        font3 = QFont()
        font3.setPointSize(8)
        self.tableWidget_3.setFont(font3)
        self.tableWidget_3.setRowCount(22)
        self.tableWidget_3.setColumnCount(6)
        self.firstLookLabel = QLabel(self.reportsTab_2)
        self.firstLookLabel.setObjectName(u"firstLookLabel")
        self.firstLookLabel.setGeometry(QRect(20, 140, 81, 16))
        self.valikko_2.addTab(self.reportsTab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 809, 21))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menu.addAction(self.actionMuokkaa)
        self.menu.addAction(self.actionTietoja_ohjelmasta)

        self.retranslateUi(MainWindow)

        self.valikko_2.setCurrentIndex(1)
        self.valikko_3.setCurrentIndex(1)
        self.valikko_4.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionMuokkaa.setText(QCoreApplication.translate("MainWindow", u"Muokkaa", None))
        self.actionTietoja_ohjelmasta.setText(QCoreApplication.translate("MainWindow", u"Tietoja ohjelmasta", None))
        self.valikko_4.setTabText(self.valikko_4.indexOf(self.studentTab_4), QCoreApplication.translate("MainWindow", u"Lainaajat", None))
        self.valikko_4.setTabText(self.valikko_4.indexOf(self.vechileTab_4), QCoreApplication.translate("MainWindow", u"Autot", None))
        self.ssnLabel.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6tunnus", None))
        self.firstnameLabel.setText(QCoreApplication.translate("MainWindow", u"Etunimi", None))
        self.lastNameLabel.setText(QCoreApplication.translate("MainWindow", u"Sukunimi", None))
        self.grupLabel.setText(QCoreApplication.translate("MainWindow", u"Ryhm\u00e4", None))
        self.vechileClassLabel.setText(QCoreApplication.translate("MainWindow", u"Ajoneuvoluokka", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Rekister\u00f6idyt lainaajat", None))
        self.savePushButton.setText(QCoreApplication.translate("MainWindow", u"Tallenna", None))
        self.valikko_4.setTabText(self.valikko_4.indexOf(self.reportsTab_4), QCoreApplication.translate("MainWindow", u"Raportit", None))
        self.valikko_3.setTabText(self.valikko_3.indexOf(self.studentTab_3), QCoreApplication.translate("MainWindow", u"Lainaajat", None))
        self.valikko_3.setTabText(self.valikko_3.indexOf(self.vechileTab_3), QCoreApplication.translate("MainWindow", u"Autot", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6tunnus", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Etunimi", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Sukunimi", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Ryhm\u00e4", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Ajoneuvoluokka", None))
        self.valikko_3.setTabText(self.valikko_3.indexOf(self.reportsTab_3), QCoreApplication.translate("MainWindow", u"Raportit", None))
        self.valikko_2.setTabText(self.valikko_2.indexOf(self.studentTab_2), QCoreApplication.translate("MainWindow", u"Lainaajat", None))
        self.registerNumberLabel.setText(QCoreApplication.translate("MainWindow", u"Rekisterinumero", None))
        self.markeLabel.setText(QCoreApplication.translate("MainWindow", u"Merkki", None))
        self.modelLabel.setText(QCoreApplication.translate("MainWindow", u"Malli", None))
        self.yearModel.setText(QCoreApplication.translate("MainWindow", u"Vuosimalli", None))
        self.personCountLabel.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6m\u00e4\u00e4r\u00e4", None))
        self.printSaveButton.setText(QCoreApplication.translate("MainWindow", u"Tallenna", None))
        self.printBarcodeButton.setText(QCoreApplication.translate("MainWindow", u"Viivakoodi", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Autoluettelo", None))
        self.valikko_2.setTabText(self.valikko_2.indexOf(self.vechileTab_2), QCoreApplication.translate("MainWindow", u"Autot", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Raportti", None))
        self.statDateLable.setText(QCoreApplication.translate("MainWindow", u"Alkaa", None))
        self.endDateLabel.setText(QCoreApplication.translate("MainWindow", u"P\u00e4\u00e4ttyy", None))
        self.printResultPushButton.setText(QCoreApplication.translate("MainWindow", u"Tulosta", None))
        self.firstLookLabel.setText(QCoreApplication.translate("MainWindow", u"Esikatselu", None))
        self.valikko_2.setTabText(self.valikko_2.indexOf(self.reportsTab_2), QCoreApplication.translate("MainWindow", u"Raportit", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"Asetukset", None))
    # retranslateUi

