# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'saveSettings.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ServerLabel = QLabel(self.centralwidget)
        self.ServerLabel.setObjectName(u"ServerLabel")
        self.ServerLabel.setGeometry(QRect(20, 10, 47, 13))
        font = QFont()
        font.setPointSize(9)
        self.ServerLabel.setFont(font)
        self.portLabel = QLabel(self.centralwidget)
        self.portLabel.setObjectName(u"portLabel")
        self.portLabel.setGeometry(QRect(20, 40, 47, 13))
        self.portLabel.setFont(font)
        self.databaseLabel = QLabel(self.centralwidget)
        self.databaseLabel.setObjectName(u"databaseLabel")
        self.databaseLabel.setGeometry(QRect(20, 70, 71, 16))
        self.databaseLabel.setFont(font)
        self.userLabel = QLabel(self.centralwidget)
        self.userLabel.setObjectName(u"userLabel")
        self.userLabel.setGeometry(QRect(20, 100, 101, 16))
        self.userLabel.setFont(font)
        self.passwordLabel = QLabel(self.centralwidget)
        self.passwordLabel.setObjectName(u"passwordLabel")
        self.passwordLabel.setGeometry(QRect(20, 130, 71, 16))
        self.passwordLabel.setFont(font)
        self.serverLineEdit = QLineEdit(self.centralwidget)
        self.serverLineEdit.setObjectName(u"serverLineEdit")
        self.serverLineEdit.setGeometry(QRect(110, 10, 151, 20))
        self.portLineEdit = QLineEdit(self.centralwidget)
        self.portLineEdit.setObjectName(u"portLineEdit")
        self.portLineEdit.setGeometry(QRect(110, 40, 151, 20))
        self.databaseLineEdit = QLineEdit(self.centralwidget)
        self.databaseLineEdit.setObjectName(u"databaseLineEdit")
        self.databaseLineEdit.setGeometry(QRect(110, 70, 151, 20))
        self.passwordLineEdit = QLineEdit(self.centralwidget)
        self.passwordLineEdit.setObjectName(u"passwordLineEdit")
        self.passwordLineEdit.setGeometry(QRect(110, 130, 151, 20))
        self.passwordLineEdit.setEchoMode(QLineEdit.Password)
        self.userLineEdit = QLineEdit(self.centralwidget)
        self.userLineEdit.setObjectName(u"userLineEdit")
        self.userLineEdit.setGeometry(QRect(110, 100, 151, 20))
        self.saveSettingspushButton = QPushButton(self.centralwidget)
        self.saveSettingspushButton.setObjectName(u"saveSettingspushButton")
        self.saveSettingspushButton.setGeometry(QRect(110, 160, 111, 31))
        font1 = QFont()
        font1.setPointSize(11)
        self.saveSettingspushButton.setFont(font1)
        self.valikko = QTabWidget(self.centralwidget)
        self.valikko.setObjectName(u"valikko")
        self.valikko.setGeometry(QRect(80, 120, 761, 821))
        self.studentTab = QWidget()
        self.studentTab.setObjectName(u"studentTab")
        self.valikko_2 = QTabWidget(self.studentTab)
        self.valikko_2.setObjectName(u"valikko_2")
        self.valikko_2.setGeometry(QRect(70, 90, 761, 821))
        self.studentTab_2 = QWidget()
        self.studentTab_2.setObjectName(u"studentTab_2")
        self.valikko_2.addTab(self.studentTab_2, "")
        self.vechileTab_2 = QWidget()
        self.vechileTab_2.setObjectName(u"vechileTab_2")
        self.valikko_2.addTab(self.vechileTab_2, "")
        self.reportsTab_2 = QWidget()
        self.reportsTab_2.setObjectName(u"reportsTab_2")
        self.label_6 = QLabel(self.reportsTab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 40, 81, 16))
        self.label_7 = QLabel(self.reportsTab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 70, 81, 16))
        self.label_8 = QLabel(self.reportsTab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 100, 81, 16))
        self.label_9 = QLabel(self.reportsTab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 130, 47, 13))
        self.label_10 = QLabel(self.reportsTab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 160, 91, 16))
        self.lineEdit_4 = QLineEdit(self.reportsTab_2)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(110, 40, 113, 20))
        self.lineEdit_6 = QLineEdit(self.reportsTab_2)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(110, 70, 113, 20))
        self.lineEdit_7 = QLineEdit(self.reportsTab_2)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(110, 100, 113, 20))
        self.lineEdit_8 = QLineEdit(self.reportsTab_2)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(110, 160, 113, 20))
        self.comboBox_2 = QComboBox(self.reportsTab_2)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(110, 130, 111, 22))
        self.valikko_2.addTab(self.reportsTab_2, "")
        self.valikko.addTab(self.studentTab, "")
        self.vechileTab = QWidget()
        self.vechileTab.setObjectName(u"vechileTab")
        self.valikko.addTab(self.vechileTab, "")
        self.reportsTab = QWidget()
        self.reportsTab.setObjectName(u"reportsTab")
        self.label = QLabel(self.reportsTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 40, 81, 16))
        self.label_2 = QLabel(self.reportsTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 70, 81, 16))
        self.label_3 = QLabel(self.reportsTab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 100, 81, 16))
        self.label_4 = QLabel(self.reportsTab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 130, 47, 13))
        self.label_5 = QLabel(self.reportsTab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 160, 91, 16))
        self.lineEdit = QLineEdit(self.reportsTab)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(110, 40, 113, 20))
        self.lineEdit_2 = QLineEdit(self.reportsTab)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(110, 70, 113, 20))
        self.lineEdit_3 = QLineEdit(self.reportsTab)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(110, 100, 113, 20))
        self.lineEdit_5 = QLineEdit(self.reportsTab)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(110, 160, 113, 20))
        self.comboBox = QComboBox(self.reportsTab)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(110, 130, 111, 22))
        self.valikko.addTab(self.reportsTab, "")
        self.valikko_3 = QTabWidget(self.centralwidget)
        self.valikko_3.setObjectName(u"valikko_3")
        self.valikko_3.setGeometry(QRect(370, 360, 761, 821))
        self.studentTab_3 = QWidget()
        self.studentTab_3.setObjectName(u"studentTab_3")
        self.valikko_3.addTab(self.studentTab_3, "")
        self.vechileTab_3 = QWidget()
        self.vechileTab_3.setObjectName(u"vechileTab_3")
        self.valikko_3.addTab(self.vechileTab_3, "")
        self.reportsTab_3 = QWidget()
        self.reportsTab_3.setObjectName(u"reportsTab_3")
        self.label_11 = QLabel(self.reportsTab_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 40, 81, 16))
        self.label_12 = QLabel(self.reportsTab_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 70, 81, 16))
        self.label_13 = QLabel(self.reportsTab_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 100, 81, 16))
        self.label_14 = QLabel(self.reportsTab_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 130, 47, 13))
        self.label_15 = QLabel(self.reportsTab_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 160, 91, 16))
        self.lineEdit_9 = QLineEdit(self.reportsTab_3)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(110, 40, 113, 20))
        self.lineEdit_10 = QLineEdit(self.reportsTab_3)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(110, 70, 113, 20))
        self.lineEdit_11 = QLineEdit(self.reportsTab_3)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(110, 100, 113, 20))
        self.lineEdit_12 = QLineEdit(self.reportsTab_3)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(110, 160, 113, 20))
        self.comboBox_3 = QComboBox(self.reportsTab_3)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(110, 130, 111, 22))
        self.valikko_4 = QTabWidget(self.reportsTab_3)
        self.valikko_4.setObjectName(u"valikko_4")
        self.valikko_4.setGeometry(QRect(0, 0, 761, 821))
        self.studentTab_4 = QWidget()
        self.studentTab_4.setObjectName(u"studentTab_4")
        self.valikko_4.addTab(self.studentTab_4, "")
        self.vechileTab_4 = QWidget()
        self.vechileTab_4.setObjectName(u"vechileTab_4")
        self.valikko_4.addTab(self.vechileTab_4, "")
        self.reportsTab_4 = QWidget()
        self.reportsTab_4.setObjectName(u"reportsTab_4")
        self.label_16 = QLabel(self.reportsTab_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 40, 81, 16))
        self.label_17 = QLabel(self.reportsTab_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 70, 81, 16))
        self.label_18 = QLabel(self.reportsTab_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 100, 81, 16))
        self.label_19 = QLabel(self.reportsTab_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 130, 47, 13))
        self.label_20 = QLabel(self.reportsTab_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 160, 91, 16))
        self.lineEdit_13 = QLineEdit(self.reportsTab_4)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(110, 40, 113, 20))
        self.lineEdit_14 = QLineEdit(self.reportsTab_4)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(110, 70, 113, 20))
        self.lineEdit_15 = QLineEdit(self.reportsTab_4)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(110, 100, 113, 20))
        self.lineEdit_16 = QLineEdit(self.reportsTab_4)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(110, 160, 113, 20))
        self.comboBox_4 = QComboBox(self.reportsTab_4)
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(110, 130, 111, 22))
        self.valikko_4.addTab(self.reportsTab_4, "")
        self.valikko_3.addTab(self.reportsTab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.passwordLineEdit, self.serverLineEdit)
        QWidget.setTabOrder(self.serverLineEdit, self.userLineEdit)
        QWidget.setTabOrder(self.userLineEdit, self.portLineEdit)
        QWidget.setTabOrder(self.portLineEdit, self.databaseLineEdit)
        QWidget.setTabOrder(self.databaseLineEdit, self.saveSettingspushButton)

        self.retranslateUi(MainWindow)

        self.valikko.setCurrentIndex(0)
        self.valikko_2.setCurrentIndex(0)
        self.valikko_3.setCurrentIndex(2)
        self.valikko_4.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.ServerLabel.setText(QCoreApplication.translate("MainWindow", u"Palvelin", None))
        self.portLabel.setText(QCoreApplication.translate("MainWindow", u"Portti", None))
        self.databaseLabel.setText(QCoreApplication.translate("MainWindow", u"Tietokanta", None))
        self.userLabel.setText(QCoreApplication.translate("MainWindow", u"K\u00e4ytt\u00e4j\u00e4tunnus", None))
        self.passwordLabel.setText(QCoreApplication.translate("MainWindow", u"Salasana", None))
        self.saveSettingspushButton.setText(QCoreApplication.translate("MainWindow", u"Tallenna", None))
        self.valikko_2.setTabText(self.valikko_2.indexOf(self.studentTab_2), QCoreApplication.translate("MainWindow", u"Lainaajat", None))
        self.valikko_2.setTabText(self.valikko_2.indexOf(self.vechileTab_2), QCoreApplication.translate("MainWindow", u"Autot", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6tunnus", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Etunimi", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Sukunimi", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Ryhm\u00e4", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Ajoneuvoluokka", None))
        self.valikko_2.setTabText(self.valikko_2.indexOf(self.reportsTab_2), QCoreApplication.translate("MainWindow", u"Raportit", None))
        self.valikko.setTabText(self.valikko.indexOf(self.studentTab), QCoreApplication.translate("MainWindow", u"Lainaajat", None))
        self.valikko.setTabText(self.valikko.indexOf(self.vechileTab), QCoreApplication.translate("MainWindow", u"Autot", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6tunnus", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Etunimi", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Sukunimi", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Ryhm\u00e4", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Ajoneuvoluokka", None))
        self.valikko.setTabText(self.valikko.indexOf(self.reportsTab), QCoreApplication.translate("MainWindow", u"Raportit", None))
        self.valikko_3.setTabText(self.valikko_3.indexOf(self.studentTab_3), QCoreApplication.translate("MainWindow", u"Lainaajat", None))
        self.valikko_3.setTabText(self.valikko_3.indexOf(self.vechileTab_3), QCoreApplication.translate("MainWindow", u"Autot", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6tunnus", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Etunimi", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Sukunimi", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Ryhm\u00e4", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Ajoneuvoluokka", None))
        self.valikko_4.setTabText(self.valikko_4.indexOf(self.studentTab_4), QCoreApplication.translate("MainWindow", u"Lainaajat", None))
        self.valikko_4.setTabText(self.valikko_4.indexOf(self.vechileTab_4), QCoreApplication.translate("MainWindow", u"Autot", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6tunnus", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Etunimi", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Sukunimi", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Ryhm\u00e4", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Ajoneuvoluokka", None))
        self.valikko_4.setTabText(self.valikko_4.indexOf(self.reportsTab_4), QCoreApplication.translate("MainWindow", u"Raportit", None))
        self.valikko_3.setTabText(self.valikko_3.indexOf(self.reportsTab_3), QCoreApplication.translate("MainWindow", u"Raportit", None))
    # retranslateUi

