# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)
import userUiRescources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 722)
        MainWindow.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon = QIcon()
        iconThemeName = u"emblem-shared"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(3000)
        MainWindow.setStyleSheet(u"background-color: rgb(223, 32, 122)")
        self.actionLopeta = QAction(MainWindow)
        self.actionLopeta.setObjectName(u"actionLopeta")
        icon1 = QIcon()
        iconThemeName = u"application-exit"
        if QIcon.hasThemeIcon(iconThemeName):
            icon1 = QIcon.fromTheme(iconThemeName)
        else:
            icon1.addFile(u".", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.actionLopeta.setIcon(icon1)
        self.actionKalle = QAction(MainWindow)
        self.actionKalle.setObjectName(u"actionKalle")
        self.actionVille = QAction(MainWindow)
        self.actionVille.setObjectName(u"actionVille")
        self.actionJaana = QAction(MainWindow)
        self.actionJaana.setObjectName(u"actionJaana")
        self.actionMikko = QAction(MainWindow)
        self.actionMikko.setObjectName(u"actionMikko")
        self.actionTallenna_nimell = QAction(MainWindow)
        self.actionTallenna_nimell.setObjectName(u"actionTallenna_nimell")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.teacgerPictureLabel = QLabel(self.centralwidget)
        self.teacgerPictureLabel.setObjectName(u"teacgerPictureLabel")
        self.teacgerPictureLabel.setGeometry(QRect(60, 180, 251, 251))
        self.teacgerPictureLabel.setPixmap(QPixmap(u"docs/Teacher.png"))
        self.keyPicturesLabel = QLabel(self.centralwidget)
        self.keyPicturesLabel.setObjectName(u"keyPicturesLabel")
        self.keyPicturesLabel.setGeometry(QRect(360, 170, 221, 261))
        self.keyPicturesLabel.setPixmap(QPixmap(u"docs/Keys.png"))
        self.readLicenceLineEdit = QLineEdit(self.centralwidget)
        self.readLicenceLineEdit.setObjectName(u"readLicenceLineEdit")
        self.readLicenceLineEdit.setGeometry(QRect(80, 450, 161, 31))
        font = QFont()
        font.setPointSize(14)
        self.readLicenceLineEdit.setFont(font)
        self.readLicenceLineEdit.setStyleSheet(u"background-color: rgb(255, 255, 127);")
        self.readyKeyLineEdit = QLineEdit(self.centralwidget)
        self.readyKeyLineEdit.setObjectName(u"readyKeyLineEdit")
        self.readyKeyLineEdit.setGeometry(QRect(360, 450, 151, 31))
        self.readyKeyLineEdit.setFont(font)
        self.readyKeyLineEdit.setStyleSheet(u"background-color: rgb(255, 255, 127);")
        self.calendarPictureLabel = QLabel(self.centralwidget)
        self.calendarPictureLabel.setObjectName(u"calendarPictureLabel")
        self.calendarPictureLabel.setGeometry(QRect(20, 520, 61, 81))
        self.calendarPictureLabel.setPixmap(QPixmap(u":/newPrefix/calendar.png"))
        self.calendarPictureLabel.setScaledContents(True)
        self.clockPictureLabel = QLabel(self.centralwidget)
        self.clockPictureLabel.setObjectName(u"clockPictureLabel")
        self.clockPictureLabel.setGeometry(QRect(330, 530, 51, 51))
        self.clockPictureLabel.setPixmap(QPixmap(u":/newPrefix/clock.png"))
        self.clockPictureLabel.setScaledContents(True)
        self.dateTimeLabel = QLabel(self.centralwidget)
        self.dateTimeLabel.setObjectName(u"dateTimeLabel")
        self.dateTimeLabel.setGeometry(QRect(100, 530, 161, 51))
        font1 = QFont()
        font1.setPointSize(24)
        self.dateTimeLabel.setFont(font1)
        self.clockTimeLabel = QLabel(self.centralwidget)
        self.clockTimeLabel.setObjectName(u"clockTimeLabel")
        self.clockTimeLabel.setGeometry(QRect(410, 530, 161, 51))
        self.clockTimeLabel.setFont(font1)
        self.goBackpushButton = QPushButton(self.centralwidget)
        self.goBackpushButton.setObjectName(u"goBackpushButton")
        self.goBackpushButton.setGeometry(QRect(580, 450, 211, 71))
        self.goBackpushButton.setFont(font)
        self.goBackpushButton.setStyleSheet(u"background-color: rgb(255, 64, 150);\n"
"color: rgb(255, 255, 255);")
        self.goBackPictureLabel = QLabel(self.centralwidget)
        self.goBackPictureLabel.setObjectName(u"goBackPictureLabel")
        self.goBackPictureLabel.setGeometry(QRect(590, 470, 31, 31))
        self.goBackPictureLabel.setStyleSheet(u"color: rgb(255, 255, 127);")
        self.goBackPictureLabel.setPixmap(QPixmap(u":/newPrefix/back.png"))
        self.goBackPictureLabel.setScaledContents(True)
        self.soundOnPictureLabel = QLabel(self.centralwidget)
        self.soundOnPictureLabel.setObjectName(u"soundOnPictureLabel")
        self.soundOnPictureLabel.setGeometry(QRect(600, 40, 141, 121))
        self.soundOnPictureLabel.setPixmap(QPixmap(u"docs/soundoff.png"))
        self.soundOnPictureLabel.setScaledContents(True)
        self.soundOffPictureLabel = QLabel(self.centralwidget)
        self.soundOffPictureLabel.setObjectName(u"soundOffPictureLabel")
        self.soundOffPictureLabel.setGeometry(QRect(600, 30, 111, 131))
        self.soundOffPictureLabel.setPixmap(QPixmap(u"docs/soundon.png"))
        self.soundOffPictureLabel.setScaledContents(True)
        self.spaceLabel = QLabel(self.centralwidget)
        self.spaceLabel.setObjectName(u"spaceLabel")
        self.spaceLabel.setGeometry(QRect(70, 90, 211, 51))
        font2 = QFont()
        font2.setPointSize(36)
        font2.setBold(True)
        self.spaceLabel.setFont(font2)
        self.spaceLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spaceLabel.setAlignment(Qt.AlignCenter)
        self.lenderNameLabel = QLabel(self.centralwidget)
        self.lenderNameLabel.setObjectName(u"lenderNameLabel")
        self.lenderNameLabel.setGeometry(QRect(80, 500, 181, 31))
        font3 = QFont()
        font3.setPointSize(16)
        self.lenderNameLabel.setFont(font3)
        self.lenderNameLabel.setAlignment(Qt.AlignCenter)
        self.carinfoLabel = QLabel(self.centralwidget)
        self.carinfoLabel.setObjectName(u"carinfoLabel")
        self.carinfoLabel.setGeometry(QRect(370, 500, 171, 31))
        self.carinfoLabel.setFont(font3)
        self.carinfoLabel.setAlignment(Qt.AlignCenter)
        self.borrowCarPushButton = QPushButton(self.centralwidget)
        self.borrowCarPushButton.setObjectName(u"borrowCarPushButton")
        self.borrowCarPushButton.setGeometry(QRect(60, 20, 191, 61))
        self.borrowCarPushButton.setFont(font1)
        self.returnCarPushButton = QPushButton(self.centralwidget)
        self.returnCarPushButton.setObjectName(u"returnCarPushButton")
        self.returnCarPushButton.setGeometry(QRect(370, 20, 191, 61))
        self.returnCarPushButton.setFont(font1)
        self.okPushButton = QPushButton(self.centralwidget)
        self.okPushButton.setObjectName(u"okPushButton")
        self.okPushButton.setGeometry(QRect(590, 320, 201, 101))
        font4 = QFont()
        font4.setPointSize(42)
        self.okPushButton.setFont(font4)
        self.keyReturnBarcodeLineEdit = QLineEdit(self.centralwidget)
        self.keyReturnBarcodeLineEdit.setObjectName(u"keyReturnBarcodeLineEdit")
        self.keyReturnBarcodeLineEdit.setGeometry(QRect(360, 450, 151, 31))
        self.keyReturnBarcodeLineEdit.setFont(font)
        self.keyReturnBarcodeLineEdit.setStyleSheet(u"background-color: rgb(255, 255, 127);")
        self.readLicenceLineEdit_2 = QLineEdit(self.centralwidget)
        self.readLicenceLineEdit_2.setObjectName(u"readLicenceLineEdit_2")
        self.readLicenceLineEdit_2.setGeometry(QRect(80, 450, 161, 31))
        self.readLicenceLineEdit_2.setFont(font)
        self.readLicenceLineEdit_2.setStyleSheet(u"background-color: rgb(255, 255, 127);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menubar.setStyleSheet(u"background-color: rgb(0, 33, 72);\n"
"color: rgb(255, 255, 255);")
        self.menuTiedosto = QMenu(self.menubar)
        self.menuTiedosto.setObjectName(u"menuTiedosto")
        self.menuEdelliset = QMenu(self.menuTiedosto)
        self.menuEdelliset.setObjectName(u"menuEdelliset")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"background-color: rgb(255, 96, 165);")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuTiedosto.menuAction())
        self.menuTiedosto.addAction(self.actionLopeta)
        self.menuTiedosto.addAction(self.menuEdelliset.menuAction())
        self.menuTiedosto.addAction(self.actionTallenna_nimell)
        self.menuEdelliset.addAction(self.actionKalle)
        self.menuEdelliset.addAction(self.actionVille)
        self.menuEdelliset.addAction(self.actionJaana)
        self.menuEdelliset.addAction(self.actionMikko)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt;\">Tallentaa henkil\u00f6n tiedot tietokantaan</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.actionLopeta.setText(QCoreApplication.translate("MainWindow", u"Lopeta", None))
#if QT_CONFIG(shortcut)
        self.actionLopeta.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionKalle.setText(QCoreApplication.translate("MainWindow", u"Kalle", None))
        self.actionVille.setText(QCoreApplication.translate("MainWindow", u"Ville", None))
        self.actionJaana.setText(QCoreApplication.translate("MainWindow", u"Jaana", None))
        self.actionMikko.setText(QCoreApplication.translate("MainWindow", u"Mikko", None))
        self.actionTallenna_nimell.setText(QCoreApplication.translate("MainWindow", u"Tallenna nimell\u00e4...", None))
        self.teacgerPictureLabel.setText("")
        self.keyPicturesLabel.setText("")
        self.readLicenceLineEdit.setText(QCoreApplication.translate("MainWindow", u"Lue ajokortti", None))
        self.readyKeyLineEdit.setText(QCoreApplication.translate("MainWindow", u"Lue avain", None))
        self.calendarPictureLabel.setText("")
        self.clockPictureLabel.setText("")
        self.dateTimeLabel.setText(QCoreApplication.translate("MainWindow", u"15.3.2024", None))
        self.clockTimeLabel.setText(QCoreApplication.translate("MainWindow", u"10.05", None))
        self.goBackpushButton.setText(QCoreApplication.translate("MainWindow", u"Kumoa", None))
        self.goBackPictureLabel.setText("")
        self.soundOnPictureLabel.setText("")
        self.soundOffPictureLabel.setText("")
        self.spaceLabel.setText(QCoreApplication.translate("MainWindow", u"Tila", None))
        self.lenderNameLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaajan nimi", None))
        self.carinfoLabel.setText(QCoreApplication.translate("MainWindow", u"merkki ja malli", None))
        self.borrowCarPushButton.setText(QCoreApplication.translate("MainWindow", u"Lainaa", None))
        self.returnCarPushButton.setText(QCoreApplication.translate("MainWindow", u"Palauta", None))
        self.okPushButton.setText(QCoreApplication.translate("MainWindow", u"ok", None))
        self.keyReturnBarcodeLineEdit.setText(QCoreApplication.translate("MainWindow", u"Lue avain", None))
        self.readLicenceLineEdit_2.setText(QCoreApplication.translate("MainWindow", u"Lue ajokortti", None))
        self.menuTiedosto.setTitle(QCoreApplication.translate("MainWindow", u"Tiedosto", None))
        self.menuEdelliset.setTitle(QCoreApplication.translate("MainWindow", u"Edelliset", None))
    # retranslateUi

